version: "3.2"

services:
  api:
    build: ./images/api
    container_name: api
    ports:
      - "80:3000"
    volumes:
      - ./images/api/src:/usr/app/src
    environment:
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "run", "test-dev"]


  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_HOST_AUTH_METHOD:  
    volumes:
      - ./_backup:/var/lib/postgresql/data        
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB "]
        interval: 5s
        timeout: 5s
        retries: 10