name: onPushDev

on:
  push:
    branches: [ develop ] 

env: 
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: dbtest
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker containers
        run: docker-compose build 

      - name: run docker containers
        run: |
          echo --- Running test cases ---
          docker-compose up --exit-code-from api
          echo --- Completed test cases ---
  
  