name: testPullReq

on:
  pull-request:
    branches: [ main , develop ] 

env: 
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: dbtest
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker containers
        run: docker-compose -f docker-compose.test.yml build

      - name: run docker containers
        run: |
          echo --- Running test cases ---
          docker-compose -f docker-compose.test.yml up --exit-code-from api
          echo --- Completed test cases ---
  